[package]
name = "hap"
version = "0.0.5"
edition = "2018"
authors = ["Elias Wilken <elias@wlkn.io>"]
description = "Rust implementation of the Apple HomeKit Accessory Protocol (HAP)"
repository = "https://github.com/ewilken/hap-rs"
readme = "README.md"
license = "MIT/Apache-2.0"

[dependencies]
eui48 = "0.4.6"
rand = "0.6.5"
uuid = { version = "0.7.2", features = ["v4", "serde"] }
serde = { version = "1.0.87", features = ["rc"] }
serde_derive = "1.0.87"
serde_json = "1.0.38"
bytes = "0.4.11"
byteorder = "1.3.1"
rust-crypto = "0.2.36"
futures = "0.1.25"
hyper = "0.12.24"
route-recognizer = "0.1.12"
libmdns = "0.2.3"
srp = "0.4.0"
sha2 = "0.8.0"
pnet = "0.22.0"
num = "0.2.0"
ring = "0.14.6"
chacha20-poly1305-aead = "0.1.2"
tokio = "0.1.15"
erased-serde = "0.3.9"
url = "1.7.2"
failure = "0.1.5"
log = "0.4.6"

[build-dependencies]
uuid = { version = "0.5.1", features = ["v4", "serde"] }
handlebars = "1.1.0"
serde = "1.0.87"
serde_derive = "1.0.87"
serde_json = "1.0.38"
