[package]
name = "hap"
version = "0.0.7"
authors = ["Elias Wilken <elias@wlkn.io>"]
edition = "2018"
description = "Rust implementation of the Apple HomeKit Accessory Protocol (HAP)"
repository = "https://github.com/ewilken/hap-rs"
readme = "README.md"
license = "MIT/Apache-2.0"

[dependencies]
byteorder = "1.3.1"
bytes = "0.4.11"
chacha20-poly1305-aead = "0.1.2"
erased-serde = "0.3.9"
eui48 = "0.4.6"
failure = "0.1.5"
futures = "0.1.25"
hyper = "0.12.24"
libmdns = "0.2.3"
log = "0.4.6"
num = "0.2.0"
pnet = "0.22.0"
rand = "0.6.5"
ring = "0.14.6"
route-recognizer = "0.1.12"
rust-crypto = "0.2.36"
serde = { version = "1.0.87", features = ["rc", "derive"] }
serde_json = "1.0.38"
sha2 = "0.8.0"
srp = "0.4.0"
tokio = "0.1.15"
url = "1.7.2"
uuid = { version = "0.7.2", features = ["v4", "serde"] }

[build-dependencies]
handlebars = "1.1.0"
rust-crypto = "0.2.36"
serde = "1.0.87"
serde_derive = "1.0.87"
serde_json = "1.0.38"
uuid = { version = "0.7.2", features = ["v4", "serde"] }
