unstable_features = true
edition = "2018"
version = "Two"

comment_width = 120
fn_single_line = true
format_code_in_doc_comments = true
format_macro_bodies = true
format_macro_matchers = true
imports_indent = "Block"
imports_layout = "HorizontalVertical"
match_arm_blocks = false
match_block_trailing_comma = true
max_width = 120
merge_imports = true
overflow_delimited_expr = true
reorder_impl_items = true
use_field_init_shorthand = true
use_try_shorthand = true
wrap_comments = true
